### PR TITLE
Adding case insensitive enum values

### PR DESCRIPTION
**Pull request by nickgw**
This change more closely mimics the functionality of [the original `dsc` module](https://forge.puppet.com/modules/puppetlabs/dsc), allowing enum values to be passed either as specified in the schema or their lowercase variants. 

Resolves Issue #216

### CODE REVIEW

**Comment by chelnak** [comment]
@nickgw Epic work thank you.

I will get this reviewed tomorrow.

**Comment by nickgw** [comment]
@chelnak thanks a bunch. Let me know if I should look into updating this with upped version numbers, changelog, etc (or if puppetlabs has any best practices around that for the repo).

**Comment by nickgw** [comment]
Hey @chelnak, you get a chance to review this?

**Review by chelnak — APPROVED** [review]
Given that the matches on Puppets Enum type are case sensitive, I think what you have proposed is fine.

The change will hopefully help out a few consumers of Puppet.Dsc.

I can cut a release for the PowerShell module as soon as tomorrow but time to re-puppetize all existing modules is undefined for now.

We can look in to individual cases ad-hoc though.


https://puppet.com/docs/puppet/6/lang_data_abstract.html#:~:text=The%20Enum%20data%20type,-The%20Enum%20data&text=It%20takes%20any%20number%20of%20strings%2C%20and%20results%20in%20a,and%20requires%20at%20least%20one.

**Comment by chelnak** [comment]
@nickgw I will merge as soon as CI finishes.

**Comment by nickgw** [comment]
@chelank, awesome, thank you! This is the list of Dsc resources I'd love to have hit:
`activedirectorydsc`,
`certificatedsc`,
`computermanagementdsc`,
`dfsdsc`,
`dnsserverdsc`,
`networkingdsc`,
`octopusdsc`,
`psdscresources`,
`securitypolicydsc`,
`sqlserverdsc`,
`storagedsc`,

Thanks again!

**Comment by chelnak** [comment]
Hey @nickgw, happy Friday!

We've just cut 1.0.4 that contains this change 🥳 

https://github.com/puppetlabs/Puppet.Dsc/releases/tag/1.0.4

Thanks again for your contribution - we will look at re-publishing modules next week.

**Pull request merged**
